#ifndef PLAYER_CONSTANTS_H
#define PLAYER_CONSTANTS_H

#define PLAYER_MOTION_DELTA_MULTIPLIER 5
#define PLAYER_HOZ_FOV_DEG 60
#define PLAYER_VERT_FOV_DEG 30
#define PLAYER_HOZ_FOV_DEG_INV (1.0f / PLAYER_HOZ_FOV_DEG)
#define PLAYER_HLF_HOZ_FOV_DEG (PLAYER_HOZ_FOV_DEG / 2)
#define PLAYER_HOZ_FOV_DEG_STEP 0.375f
#define PLAYER_HOZ_FOV_DEG_STEP_INV (1.0f / PLAYER_HOZ_FOV_DEG_STEP)
#define PLAYER_W 8.0f
#define PLAYER_H 8.0f
#define PLAYER_INTERACTION_DISTANCE 4.0f
#define PLAYER_ROTATION_SPEED 30.0f
#define PLAYER_ROTATION_STEP 6.0f
#define PLAYER_SPEED 25.0f
#define PROJECTION_PLANE_DISTANCE (WINDOW_W / 2) / tan(PLAYER_FOV_DEG / 2 * M_PI / 180.0)
#define SPRINT_SPEED_INCREASE 15.0f

#endif