#ifndef CONFIG_CONSTANTS_H
#define CONFIG_CONSTANTS_H

#define WINDOW_W 1600
#define WINDOW_H 800
#define WINDOW_HLF_W (WINDOW_W / 2)
#define WINDOW_HLF_H (WINDOW_H / 2)
#define WINDOW_QRT_W (WINDOW_W / 4)
#define WINDOW_QRT_H (WINDOW_H / 4)

#endif